name: Publish

inputs:
  isRelease:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:

  - name: Download Artifacts
    uses: actions/download-artifact@v3
    with:
      name: packages
      path: ${{ github.workspace }}/packages

  - name: Download Prerequisites
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
      chmod u+x ./update-release

  - name: Publish on GitHub (Release)
    if: ${{ inputs.isRelease == 'true' }}
    shell: bash
    run: |
      set -ex
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/plot -t ${{ env.mildredVersion }} -n "${{ env.mildredVersion }}" -f ReleaseNotes.md -e packages/*.zip

  - name: Publish on GitHub (Continuous)
    if: ${{ inputs.isRelease == 'false' }}
    shell: bash
    run: |
      set -ex
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/plot -t continuous -n "Continuous (${{ env.mildredVersion }})" -b "Continuous release from \`develop\`. Built $(date)." -e packages/*.zip
