parameters:
  - name: continuous
    default: false
    type: boolean

jobs:
  - job: 'release_gh'
    displayName: 'Create Versioned Release (GH)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
          chmod u+x ./update-release
        displayName: 'Install Prerequisites'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-cli-artifacts'
        displayName: 'Download Linux Artifacts'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'osx-artifacts'
        displayName: 'Download OSX Artifacts'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'windows-artifacts'
        displayName: 'Download Windows Artifacts'
      - bash: |
          set -ex
          VERSION=`grep "#define MILDREDVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
          ./update-release -r disorderedmaterials/plot -t ${VERSION} -n "${VERSION}" -f ReleaseNotes.md $(System.ArtifactsDirectory)/linux-*-artifacts/* $(System.ArtifactsDirectory)/windows-artifacts/* $(System.ArtifactsDirectory)/osx-artifacts/*
        condition: eq('${{ parameters.continuous }}', false)
        env:
          GITHUB_TOKEN: $(REPO_SECRET)
        displayName: 'Create Versioned Release (GitHub)'
      - bash: |
          set -ex
          SHORTHASH=`git rev-parse --short HEAD`
          DATE=`date`
          VERSION=`grep "#define MILDREDVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
          ./update-release -r disorderedmaterials/plot -t continuous -n "Continuous Build (${VERSION} @ ${SHORTHASH})" -b "Continuous release from current \`develop\` branch at ${SHORTHASH}. Built ${DATE}." -p -e -u $(System.ArtifactsDirectory)/linux-*-artifacts/* $(System.ArtifactsDirectory)/windows-artifacts/* $(System.ArtifactsDirectory)/osx-artifacts/*
        condition: eq('${{ parameters.continuous }}', true)
        env:
          GITHUB_TOKEN: $(REPO_SECRET)
        displayName: 'Create Release (GitHub)'
      - bash: |
          set -ex
          ./ci/scripts/list-releases -r disorderedmaterials/plot -u -v $(Build.SourceBranchName)
        condition: eq('${{ parameters.continuous }}', false)
        env:
          GITHUB_TOKEN: $(REPO_SECRET)
        displayName: 'Update Web Release Info'
