parameters:
  - name: qtver
    default: 6.2.2

steps:
  - bash: |
      pip3 install dmgbuild biplist
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-dmg
      chmod u+x ./prep-dmg
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      Qt6_ROOT=/tmp/qt/${{ parameters.qtver }}/macos/
      # Get program version
      MILDRED_VERSION=`grep "#define MILDREDVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
      ./prep-dmg -a Mildred-GUI -v ${MILDRED_VERSION} -b build/bin/dissolve-gui.app/Contents/MacOS/dissolve-gui -d ${Qt6_ROOT} -i icon/icon-1024x1024.png -p build/bin/dissolve-gui.app/Contents/Info.plist
    displayName: 'Prepare DMG Dirs'
  - bash: |
      set -ex
      # Get program version
      MILDRED_VERSION=`grep "#define MILDREDVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
      # Fix icon link
      sed -i -e "s/Mildred.icns/Mildred-GUI.icns/g" Mildred-GUI-${MILDRED_VERSION}/Mildred-GUI.app/Contents/Info.plist
      # Create DMG
      dmgbuild -s ci/osx/dmgbuild-settings.py -D app=./Mildred-GUI-${MILDRED_VERSION}/Mildred-GUI.app -D icon=./Mildred-GUI-${MILDRED_VERSION}/Mildred-GUI.app/Contents/Resources/Mildred-GUI.icns "Mildred GUI" Mildred-GUI-${MILDRED_VERSION}.dmg
    displayName: 'Create Disk Images'
  - bash: |
      set -ex
      mkdir packages
      mv Mildred*.dmg packages
    displayName: 'Move Artifacts'
