trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - "*"
  paths:
    exclude:
    - examples/*
    - README.md
    - .azure-pipelines/continuous.yml
    - .azure-pipelines/release.yml

stages:
  - template: templates/code-quality-checks.yml

  # Build Executables
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: 'linux'
        displayName: 'Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-linux.yml
          - template: templates/package-zip.yml
            parameters:
              suffix: 'linux'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
      - job: "osx"
        displayName: "OSX"
        pool:
          vmImage: "macOS-10.15"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-osx.yml
          - template: templates/package-zip.yml
            parameters:
              suffix: 'osx'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: "osx-artifacts"
            displayName: "Publish OSX Artifacts"
      - job: "windows"
        displayName: "Windows"
        pool:
          vmImage: "windows-2022"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/set-short-hash.yml
          - template: templates/build-windows.yml
          - template: templates/package-zip.yml
            parameters:
              suffix: 'win64'
              zipcommand: "7z a"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: "windows-artifacts"
            displayName: "Publish Windows Artifacts"
